### ISSUE TITLE
Suggestion: Change to the existing veins system

### ISSUE THREAD

**Issue by alpe12** [backrunner/DSPResourceMod#2]
It would be better if the F7 option would apply the resouce multiplier rate to every node, instead of the same value (default 100000000).

Eg: If a save current resource multiplier is 1.5x and the mod MultipilerRate option is 3, it should double (3 / 1,5 = 2) the value of all existing resource veins.

**Comment by backrunner** [comment]
I've uploaded the v1.1, you can try it.

**Comment by alpe12** [comment]
Thanks.
